# Generated by Django 2.1.2 on 2018-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('Firstname', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Phonenumber', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Caste', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('District', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
            ],
        ),
    ]
