# Generated by Django 2.1.2 on 2018-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Eventname', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='Email',
            field=models.EmailField(max_length=20),
        ),
    ]
