# Generated by Django 2.1.2 on 2018-11-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0002_auto_20181108_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Time',
            field=models.TimeField(),
        ),
    ]
